### ISSUE TITLE
Error: Cannot find module 'dateformat'

### ISSUE THREAD

**Issue by aknap** [olefredrik/FoundationPress#1132]
**How can this bug be reproduced?**

I just installed FoundationPress and ran "npm start" as usual, according to the way it is described in the readme file.

1. git clone FoundationPress
2. npm install
3. npm start

I already tried doing a clean install several times, also cleaned npm cache.

**What happened instead?**
The npm-debug.log file is here: [npm-debug.log](https://github.com/olefredrik/FoundationPress/files/1387728/npm-debug.log)

Console output (I'm using cmder):
```
λ npm start

> foundationpress@2.10.4 start c:\WampServer\www\biss\wp-content\themes\FoundationPress
> gulp

[15:58:51] Requiring external module babel-register
module.js:340
    throw err;
    ^

Error: Cannot find module 'dateformat'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (c:/WampServer/www/biss/wp-content/themes/FoundationPress/gulpfile.babel.js:11:1)
    at Module._compile (module.js:435:26)
    at loader (c:\WampServer\www\biss\wp-content\themes\FoundationPress\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (c:\WampServer\www\biss\wp-content\themes\FoundationPress\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.10.4 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundationpress@2.10.4 start script 'gulp'.
npm ERR! This is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\WampServer\www\biss\wp-content\themes\FoundationPress\npm-debug.log
```

**Please List the Following:**
* OS & version: Windows 10 x64 (Windows_NT 10.0.15063)
* Node version (node -v) [Node v4+ is required] : v4.2.4
* FoundationPress version (see line 3 in package.json): 2.10.4
* Foundation version (see dependencies in package.json): 6.4.1

Please let me know if I can provide further useful info.

**Comment by colin-marshall** [comment]
run `npm install dateformat --save-dev`. Looks like it didn't get added to `package.json` in a recent update.

**Comment by aknap** [comment]
Thanks Colin, that did the trick!

**Comment by colin-marshall** [comment]
No problem! Fixed in https://github.com/olefredrik/FoundationPress/commit/be067dc661e633d3d5bb8a7faa4c99819fc9250a
