### ISSUE TITLE
Cannot Find Module....

### ISSUE THREAD

**Issue by niks-230688** [olefredrik/FoundationPress#1184]
D:\xampp\htdocs>f7 create myapp com.example.myapp MyApp --template [singleview]
Creating new Framework7 app
Creating a new cordova project.
Downloading scripts & hooks
Error: EPERM: operation not permitted, rename 'D:\xampp\htdocs\1513071810089-728
496851360386\framework7-cli-scripts-master' -> 'D:\xampp\htdocs\myapp\scripts'
  Downloading scripts & hooks √
module.js:544
    throw err;
    ^

Error: Cannot find module 'D:\xampp\htdocs\myapp\scripts\hooks.json'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at C:\Users\Nikul\AppData\Roaming\npm\node_modules\framework7-cli\commands.j
s:63:33
    at GithubDownloader.<anonymous> (C:\Users\Nikul\AppData\Roaming\npm\node_mod
ules\framework7-cli\utils\download-github.js:17:21)
    at GithubDownloader.emit (events.js:159:13)
    at C:\Users\Nikul\AppData\Roaming\npm\node_modules\framework7-cli\node_modul
es\github-download\lib\github-download.js:134:19
    at next (C:\Users\Nikul\AppData\Roaming\npm\node_modules\framework7-cli\node
_modules\rimraf\rimraf.js:75:7)
    at FSReqWrap.CB [as oncomplete] (C:\Users\Nikul\AppData\Roaming\npm\node_mod
ules\framework7-cli\node_modules\rimraf\rimraf.js:111:9)

**Comment by colin-marshall** [comment]
I don't believe this has anything to do with FoundationPress. Closing.
