### ISSUE TITLE
Build failing (probably) because of webpack dependencies

### ISSUE THREAD

**Issue by martinkrcho** [olefredrik/FoundationPress#1192]
Build of my project based on FoundationPress started failing to build today. I haven't changed anything at all since the last succesfull build.

**How can this bug be reproduced?**

1. Download fresh copy of FoundationPress.
2. run npm install
3. npm run-script build

**What did you expect to happen?**

I expected the build to finish successfully with no errors.

**What happened instead?**

I got the following error trace:

```
[11:58:07] Starting 'build'...
[11:58:07] Starting 'clean'...
[11:58:07] Finished 'clean' after 3.14 ms
[11:58:07] Starting 'sass'...
[11:58:10] Finished 'sass' after 2.79 s
[11:58:10] Starting 'javascript'...
[11:58:14] 'javascript' errored after 3.62 s
[11:58:14] TypeError: file.isSymbolic is not a function
    at DestroyableTransform.normalize [as _transform] (/buddy/mojandroid-sk/wp-content/themes/mawi/node_modules/gulp/node_modules/vinyl-fs/lib/dest/prepare.js:31:15)
    at DestroyableTransform.Transform._read (/buddy/mojandroid-sk/wp-content/themes/mawi/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/buddy/mojandroid-sk/wp-content/themes/mawi/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/buddy/mojandroid-sk/wp-content/themes/mawi/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/buddy/mojandroid-sk/wp-content/themes/mawi/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/buddy/mojandroid-sk/wp-content/themes/mawi/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (/buddy/mojandroid-sk/wp-content/themes/mawi/node_modules/duplexify/index.js:201:22)
    at doWrite (/buddy/mojandroid-sk/wp-content/themes/mawi/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/buddy/mojandroid-sk/wp-content/themes/mawi/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Pumpify.Writable.write (/buddy/mojandroid-sk/wp-content/themes/mawi/node_modules/readable-stream/lib/_stream_writable.js:322:11)
[11:58:14] 'build' errored after 6.41 s
npm info lifecycle mawi-wp-theme@2.10.4~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mawi-wp-theme@2.10.4 build: `gulp build --production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mawi-wp-theme@2.10.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

* OS & version: Windows 10
* Node version (node -v) [Node v4+ is required] : v6.5.0
* FoundationPress version (see line 3 in package.json): 2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) : 6.4.3

**Possible solution**

Replace versions of webpack and webpack-stream dependencies in package.json with the following:
```
"webpack": "^3.10.0",
"webpack-stream": "^4.0.0",
```

**Comment by GarySwift** [comment]
You are not alone. I am getting the same issue in Mac OS also using FP version 2.10.4.

2.10.3 is still working in my environment.

**Comment by colin-marshall** [comment]
@martinkrcho I updated some packages (credit @alexbohariuc) in `package.json` that were causing this issue. Please try now and see if your issue is resolved. If not, we will continue discussion of the problem in #1193.

**Comment by martinkrcho** [comment]
Thanks, guys.
