### ISSUE TITLE
npm start is failing (TypeError: file.isSymbolic is not a function)

### ISSUE THREAD

**Issue by GarySwift** [olefredrik/FoundationPress#1193]
**How can this bug be reproduced?**

1. Step one
npm install
2. Step two
npm start

**What did you expect to happen?**
npm start should have completed and launched Browsersync

**What happened instead?**
It failed listing some npm errors. Main error:

[12:07:15] 'webpack:build' errored after 1.52 s
[12:07:15] TypeError: file.isSymbolic is not a function

**Summary**
Clean installs of the latest FoundationPress are failing on my MacBook.  Older versions are working fine (2.10.3).

Any tips on getting this resolved would be appreciated.

**Debug Log**
[https://www.dropbox.com/s/rm910m9xg8ekqm0/foundationpress-console-error.pdf?dl=0](https://www.dropbox.com/s/rm910m9xg8ekqm0/foundationpress-console-error.pdf?dl=0)
(colour coded pdf for easier reading)

* OS & version: Mac OS Sierra 10.12.6
* Node version : v5.4.1
* FoundationPress version: 2.10.4
* Foundation version : foundation-sites@6.4.3

**Comment by Flewps** [comment]
I have the same problem. I have tried with diferent versions of node and npm and every launch the same error:

`TypeError: file.isSymbolic is not a function
    at DestroyableTransform.normalize [as _transform] (/home/si2/SI2/TEST/FoundationPress/node_modules/vinyl-fs/lib/dest/prepare.js:31:15)
    at DestroyableTransform.Transform._read (/home/si2/SI2/TEST/FoundationPress/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/home/si2/SI2/TEST/FoundationPress/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/si2/SI2/TEST/FoundationPress/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/si2/SI2/TEST/FoundationPress/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/home/si2/SI2/TEST/FoundationPress/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (/home/si2/SI2/TEST/FoundationPress/node_modules/duplexify/index.js:201:22)
    at doWrite (/home/si2/SI2/TEST/FoundationPress/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/si2/SI2/TEST/FoundationPress/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Pumpify.Writable.write (/home/si2/SI2/TEST/FoundationPress/node_modules/readable-stream/lib/_stream_writable.js:322:11)`

**Comment by peterbaio** [comment]
this is happening to me all of a sudden.

**Comment by alexbohariuc** [comment]
Try to change the following versions in package.json:

```
"babel-loader": "^8.0.1",
"webpack": "^3.10.0",
"webpack-stream": "^4.0.0",
```

Also, would be useful to run:

```
rm -rf node_modules
npm cache clean
```

and again

`npm install
`

**Comment by colin-marshall** [comment]
Thanks @alexbohariuc for the fix!

**Comment by Flewps** [comment]
Thanks @alexbohariuc !!

**Comment by colin-marshall** [comment]
Closing this. Feel free to reopen if not resolved.
