### ISSUE TITLE
JS Error when running build

### ISSUE THREAD

**Issue by pyrodie18** [olefredrik/FoundationPress#1242]
I am trying to run the `npm run build` command and am currently getting an error when it starts to minify the JS.

**How can this bug be reproduced?**

1. Just run `npm run build`

**What did you expect to happen?**
A successful build process

**What happened instead?**
c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief>npm run package

> foundationpress@2.10.4 package c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief
> gulp package --production

[22:05:15] Requiring external module babel-register
[22:05:16] Loading config file...
[22:05:16] config.yml does not exist, loading config-default.yml
[22:05:16] Using gulpfile c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\gulpfile.babel.js
[22:05:16] Starting 'package'...
[22:05:16] Starting 'build'...
[22:05:16] Starting 'clean'...
[22:05:16] Finished 'clean' after 36 ms
[22:05:16] Starting 'sass'...
[22:05:16] Starting 'webpack:build'...
[22:05:16] Starting 'images'...
[22:05:16] Starting 'copy'...
[22:05:17] Finished 'copy' after 622 ms
[22:05:18] Finished 'sass' after 2.23 s
[22:05:18] gulp-imagemin: Minified 7 images (saved 56.28 kB - 23.4%)
{ Error
    at new JS_Parse_Error (eval at <anonymous> (c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1542:11)
    at parse_error (eval at <anonymous> (c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1667:9)
    at Object.next_token [as input] (eval at <anonymous> (c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2075:25)
    at maybe_conditional (eval at <anonymous> (c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2834:13)
    at maybe_assign (eval at <anonymous> (c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2856:20)
    at expression (eval at <anonymous> (c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2875:20)
    at expr_atom (eval at <anonymous> (c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2608:26)
    at maybe_unary (eval at <anonymous> (c:\xampp\htdocs\signal-chief\wp-content\themes\Signal-Chief\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2792:19)
  message: 'c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\app.js: Unexpected character \'`\'',
  fileName: 'c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\app.js',
  lineNumber: 106,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1534:18)\n    at js_error (eval at <anonymous> (c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1542:11)\n    at parse_error (eval at <anonymous> (c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1667:9)\n    at Object.next_token [as input] (eval at <anonymous> (c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1946:9)\n    at next (eval at <anonymous> (c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2075:25)\n    at maybe_conditional (eval at <anonymous> (c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2834:13)\n    at maybe_assign (eval at <anonymous> (c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2856:20)\n    at expression (eval at <anonymous> (c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2875:20)\n    at expr_atom (eval at <anonymous> (c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2608:26)\n    at maybe_unary (eval at <anonymous> (c:\\xampp\\htdocs\\signal-chief\\wp-content\\themes\\Signal-Chief\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2792:19)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }
[22:05:19] Version: webpack 3.10.0
 Asset     Size  Chunks             Chunk Names
app.js  96.8 kB       0  [emitted]  app
[22:05:19] Finished 'images' after 2.5 s
[22:05:19] The following tasks did not complete: package, build, <parallel>, webpack:build
[22:05:19] Did you forget to signal async completion?

**Please List the Following:**
* OS & version:  Windows 10
* Node version (node -v) [Node v4+ is required] : 8.9.4
* FoundationPress version (see line 3 in package.json): 2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) :  6.4.3

**Comment by JPOak** [comment]
@pyrodie18 You will most likely want to see this thread #1219 since you are on Windows and notice my last comment in the thread as well referencing a issue with interchange images. This really needs to be combined into Master.

**Comment by pyrodie18** [comment]
Good call @JPOak , thanks a ton.  Agree that this needs to be included in the Master.  In the mean time, closing this.

Thanks,

Troy
