### ISSUE TITLE
Do I have a npm/node issue or is it something else? I'm getting this error after updating OSX to the latest

### ISSUE THREAD

**Issue by roborracle** [olefredrik/FoundationPress#1293]
I've tried to `npm start` in my project, but it keeps failing. I've been looking through node and npm and I'm not seeing any issues there, but I remember last time I updated OSX I had issues, just hoping to avoid having to completely remove that again - that sucked.

I thought it may have been because my project was somehow corrupted, so I cloned in a new copy of FP and ran `npm install` and I'm getting the same kind of errors. To be clear, what I'm seeing below is from the fresh clone I just pulled in.

Here is what I'm seeing in the command line:

``` 
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/sass.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node" "/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rob/.npm/_logs/2018-07-13T12_54_55_726Z-debug.log
rob@Roberts-iMac:/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress$ npm run build

> foundationpress@2.10.4 build /Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress
> gulp build --production

[08:55:27] Requiring external module babel-register
[08:55:34] Loading config file...
[08:55:34] config.yml does not exist, loading config-default.yml
[08:55:35] Using gulpfile /Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress/gulpfile.babel.js
[08:55:35] Starting 'build'...
[08:55:35] Starting 'clean'...
[08:55:35] Finished 'clean' after 4.01 ms
[08:55:35] Starting 'sass'...
[08:55:35] Starting 'webpack:build'...
[08:55:35] Starting 'images'...
[08:55:35] Starting 'copy'...
[08:55:35] 'sass' errored after 223 ms
[08:55:35] Error: Cannot find module 'gulp-sass' from '/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress'
    at Function.module.exports [as sync] (/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress/node_modules/resolve/lib/sync.js:40:15)
    at requireFn (/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress/node_modules/gulp-load-plugins/index.js:74:25)
    at Object.get [as sass] (/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress/node_modules/gulp-load-plugins/index.js:117:41)
    at sass (/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress/gulpfile.babel.js:82:13)
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at asyncRunner (/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[08:55:35] 'build' errored after 260 ms
[08:55:35] The following tasks did not complete: webpack:build, images, copy
[08:55:35] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundationpress@2.10.4 build: `gulp build --production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.10.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rob/.npm/_logs/2018-07-13T12_55_35_296Z-debug.log
```

and here is what's being output in to that log entry.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle foundationpress@2.10.4~prebuild: foundationpress@2.10.4
6 info lifecycle foundationpress@2.10.4~build: foundationpress@2.10.4
7 verbose lifecycle foundationpress@2.10.4~build: unsafe-perm in lifecycle true
8 verbose lifecycle foundationpress@2.10.4~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress/node_modules/.bin:/Applications/MAMP/Library/bin/:/Applications/MAMP/bin/php/php7.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
9 verbose lifecycle foundationpress@2.10.4~build: CWD: /Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress
10 silly lifecycle foundationpress@2.10.4~build: Args: [ '-c', 'gulp build --production' ]
11 silly lifecycle foundationpress@2.10.4~build: Returned: code: 1  signal: null
12 info lifecycle foundationpress@2.10.4~build: Failed to exec build script
13 verbose stack Error: foundationpress@2.10.4 build: `gulp build --production`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid foundationpress@2.10.4
15 verbose cwd /Applications/MAMP/htdocs/acc-fcri/wp-content/themes/FoundationPress
16 verbose Darwin 17.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.6.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error foundationpress@2.10.4 build: `gulp build --production`
22 error Exit status 1
23 error Failed at the foundationpress@2.10.4 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
I've tried looking through other similar issues, but nothing I've seen has helped me get to where I can start working on my project again, or even getting this new FP instance running properly. 

Any feedback/input/advice would be most welcome.

**Comment by JPOak** [comment]
@roborracle I just tried a fresh clone on a fully updated Mac and it worked fine for me.

Maybe you already tried:
- Fully update you Node.js
- Is it some weird permission issue? Try cloning to a folder on your desktop and running.
- Rebuild your node-sass (older projects)
- Delete module directory and  install again
- Run npm update

**Comment by linuxbastard** [comment]
It does look like node-sass is failing. Have you tried running `npm install --save-dev node-sass` again?

**Comment by roborracle** [comment]
Indeed I did.  but I keep getting the following:

```
user@imac:/Applications/MAMP/htdocs/acc-fcri/wp-content/themes/acc-fcri$ npm install --save-dev node-sass

> node-sass@4.9.2 install /Applications/MAMP/htdocs/acc-fcri/wp-content/themes/acc-fcri/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.2/darwin-x64-64_binding.node
Download complete░░⸩ ⠋ :
Binary saved to /Applications/MAMP/htdocs/acc-fcri/wp-content/themes/acc-fcri/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Caching binary to /Users/SMG_Rob/.npm/node-sass/4.9.2/darwin-x64-64_binding.node

> node-sass@4.9.2 postinstall /Applications/MAMP/htdocs/acc-fcri/wp-content/themes/acc-fcri/node_modules/node-sass
> node scripts/build.js

Binary found at /Applications/MAMP/htdocs/my-project/wp-content/themes/acc-fcri/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
+ node-sass@4.9.2
added 16 packages from 19 contributors, updated 10 packages, moved 1 package and audited 22641 packages in 19.251s
found 18 vulnerabilities (2 low, 16 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
```

`npm audit fix` doesn't resolve the issue and it continues to fail on `npm run build`

**Comment by roborracle** [comment]
Just fyi - in case anyone else runs in to this in the future, I just removed completely and reinstalled node and that seems to have fixed my error.
