### ISSUE TITLE
Unhandled rejection Error: Command failed: /usr/bin/git checkout 4.0scriptor@1.0.0

### ISSUE THREAD

**Issue by asmundsollihogda** [olefredrik/FoundationPress#1316]
Hi! Thanks for great work. I have problems with installing NPM and think that it might be since updating macOS. 

**How can this bug be reproduced?**

1. Install foundationpress
2. run npm install

**What happened instead?**

Unhandled rejection Error: Command failed: /usr/bin/git checkout 4.0scriptor@1.0.0
error: pathspec '4.0' did not match any file(s) known to git.

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

* OS & version: macOS 10.14
* Node version (node -v) [Node v4+ is required] : v10.12.0
* FoundationPress version (see line 3 in package.json): 2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) :

**Comment by prahladmishra** [comment]
I am getting the same error.

**Comment by RonEarl** [comment]
I posted the same issue a little big ago. 

Frustrating. I think it's an issue getting the correct version of Gulp checked out.

-Ron

**Comment by RonEarl** [comment]
Hi DeiCha,

That did not work for me. I got the same error.

-Ron

**Comment by asmundsollihogda** [comment]
Reinstalling git as a clean install and changing:
package.json line 42 from "gulp": "gulpjs/gulp#4.0", to "gulp": "4.0"
...helped me solve this problem.

Thank you for your help! @DeiCha

**Comment by michalchovanak** [comment]
changing "gulp": "gulpjs/gulp#4.0", to "gulp": "4.0" helped me, thank you!

**Comment by Pixelsmith** [comment]
I ran into the same wall that @RonEarl did. I'm a certified N00b, but the current version of the theme on Github comes with package-lock.json pre-installed, even though I'm not seeing it listed on the file list on Github.

If I make @DeiCha 's change on line 42 **and** delete the package-lock.json file **then** I can get NPM install to work, and the package-lock.json reappears after install.

I'm using git clone via Windows command line to install the theme, but I can't imagine why that'd auto-create the package-lock.json file.

**Comment by BakaloMykhailo** [comment]
Thanks @DeiCha, changing "gulp": "gulpjs/gulp#4.0", to "gulp": "4.0" works

**Comment by DylanReile** [comment]
I believe what happened is that the gulpjs team deleted the branch `4.0` when they released that version as a package. @DeiCha 's fix targets that release instead of the git branch directly.

**Comment by jlriveroweb** [comment]
Thanks @DeiCha changing "gulp": "gulpjs/gulp#4.0", to "gulp": "4.0" helped me, thank you!

**Comment by bbuilds** [comment]
So I was able to get the dependencies to install, but browser sync doesn't watch my files now.

Anyone else have this issue? DOesn't watch my JS or SCSS files.

**Comment by millturnK** [comment]
You shouldn't need to downgrade node. All I did was this and it amended my package and package-lock files appropriately:
npm install gulp@next --save

**Comment by alexander-young** [comment]
The reference to `gulpjs/gulp#4.0` wasn't in the `package.json` but it was still in the `package-lock.json` and had to delete it out of there and then re-install the packages.
