### ISSUE TITLE
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)

### ISSUE THREAD

**Issue by asmundsollihogda** [olefredrik/FoundationPress#1317]
Hi Guys, 

This happens when I try to run npm start. Any ideas? Tried to update gulp, npm and node.js.

Thanks!

Code:

$ npm start

```
> foundationpress@2.10.4 start /Applications/MAMP/htdocs/ot5/wp-content/themes/OT_1.6
> gulp

```
```
[17:40:45] Requiring external module babel-register
[17:40:46] Loading config file...
[17:40:46] config.yml exists, loading config.yml
[17:40:46] Using gulpfile /Applications/MAMP/htdocs/ot5/wp-content/themes/OT_1.6/gulpfile.babel.js
[17:40:46] Starting 'default'...
[17:40:46] Starting 'build'...
[17:40:46] Starting 'clean'...
[17:40:46] Finished 'clean' after 2.16 ms
[17:40:46] Starting 'sass'...
[17:40:46] Starting 'webpack:build'...
[17:40:46] Starting 'images'...
[17:40:46] Starting 'copy'...
[17:40:46] 'sass' errored after 37 ms
[17:40:46] Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.7.2
    at module.exports (/Applications/MAMP/htdocs/ot5/wp-content/themes/OT_1.6/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Applications/MAMP/htdocs/ot5/wp-content/themes/OT_1.6/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/MAMP/htdocs/ot5/wp-content/themes/OT_1.6/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
[17:40:46] 'build' errored after 41 ms
[17:40:46] 'default' errored after 43 ms
[17:40:46] The following tasks did not complete: webpack:build, images, copy
[17:40:46] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundationpress@2.10.4 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.10.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

OS & version: macOS 10.14
Node version (node -v) [Node v4+ is required] : v10.12.0
FoundationPress version (see line 3 in package.json): 2.10.4

```

**Comment by asmundsollihogda** [comment]
Reinstalling git helped solve this.
