### ISSUE TITLE
issue with npm run dev

### ISSUE THREAD

**Issue by hoangtuantx92** [olefredrik/FoundationPress#1369]
> **when I try to run command npm run dev, I got this error. And it was working fine last night. Can someone help me**

> concurrently "npm run server" "npm run client"

[0] 
[0] > myportfoliosite@0.1.0 server /Users/kevindo/Desktop/myportfoliosite
[0] > nodemon index.js
[0] 
[1] 
[1] > myportfoliosite@0.1.0 client /Users/kevindo/Desktop/myportfoliosite
[1] > npm run start --prefix client
[1] 
[1] 
[1] > myportfoliosite@0.1.0 start /Users/kevindo/Desktop/myportfoliosite/client
[1] > node index.js
[1] 
[0] [nodemon] 1.18.10
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[0] [nodemon] starting `node index.js`
[1] internal/modules/cjs/loader.js:651
[1]     throw err;
[1]     ^
[1] 
[1] Error: Cannot find module '/Users/kevindo/Desktop/myportfoliosite/client/index.js'
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:575:25)
[1]     at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
[1]     at internal/main/run_main_module.js:21:11
[1] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[1] npm ERR! myportfoliosite@0.1.0 start: `node index.js`
[1] npm ERR! Exit status 1
npm ERR! 
[1] npm ERR! Failed at the myportfoliosite@0.1.0 start script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] 
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /Users/kevindo/.npm/_logs/2019-03-14T17_01_50_393Z-debug.log
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! myportfoliosite@0.1.0 client: `npm run start --prefix client`
[1] npm ERR! Exit status 1
npm ERR! 
[1] npm ERR! Failed at the myportfoliosite@0.1.0 client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] 
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /Users/kevindo/.npm/_logs/2019-03-14T17_01_50_411Z-debug.log
[1] npm run client exited with code 1
[0] Server listening on port ${PORT}
^C[0] npm run server exited with code 0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myportfoliosite@0.1.0 dev: `concurrently "npm run server" "npm run client"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myportfoliosite@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kevindo/.npm/_logs/2019-03-14T17_01_59_638Z-debug.log

`"scripts": {
    "start": "node index.js",
    "server": "nodemon index.js",
    "client": "npm run start --prefix client",
    "dev": "concurrently \"npm run server\" \"npm run client\""
  },`

**Comment by derweili** [comment]
Could you please post the following information:

- OS & version:
- Node version (node -v) [Node v6+ is required] :
- FoundationPress version (see line 3 in package.json):
- Foundation version (found in node_modules/foundation-sites/package.json) :

**Comment by hoangtuantx92** [comment]
yes!
os version: 10.14.1
node version: 11.11.0
FoundationPress version:0.1.0
Foundation version (found in node_modules/foundation-sites/package.json) : I don't have it in my node_module... umm this is weird
