### ISSUE TITLE
Cannot find module './access-error.js'

### ISSUE THREAD

**Issue by nitin20212** [olefredrik/FoundationPress#1370]
Getting error while installing npm

 verbose stack Error: Cannot find module './access-error.js'
4 verbose stack     at Function.Module._resolveFilename (module.js:547:15)
4 verbose stack     at Function.Module._load (module.js:474:25)
4 verbose stack     at Module.require (module.js:596:17)
4 verbose stack     at require (internal/module.js:11:18)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/install/exists.js:4:19)
4 verbose stack     at Module._compile (module.js:652:30)
4 verbose stack     at Object.Module._extensions..js (module.js:663:10)
4 verbose stack     at Module.load (module.js:565:32)
4 verbose stack     at tryModuleLoad (module.js:505:12)
4 verbose stack     at Function.Module._load (module.js:497:3)
4 verbose stack     at Module.require (module.js:596:17)
4 verbose stack     at require (internal/module.js:11:18)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/install/check-permissions.js:8:14)
4 verbose stack     at Module._compile (module.js:652:30)
4 verbose stack     at Object.Module._extensions..js (module.js:663:10)
4 verbose stack     at Module.load (module.js:565:32)

**Comment by derweili** [comment]
Could you please post the following information:

- OS & version:
- Node version (node -v) [Node v6+ is required] :
- npm Version (npm -v)
- FoundationPress version (see line 3 in package.json):
- Foundation version (found in node_modules/foundation-sites/package.json) :


This does not look like an error with FoundationPress. I guess it's something with npm. Maybe try to reinstall npm.

https://npm.community/t/unable-to-install-npm-packages-after-npm-update/4856

**Comment by AshokICreate** [comment]
i did ```nvm use 11``` and then ```npm install```
