### ISSUE TITLE
Initial Build Erroring

### ISSUE THREAD

**Issue by BlackSheepWithMe** [olefredrik/FoundationPress#558]
Just npm installed, and cant run `npm run build` without this error

```
> foundationpress@1.7.0 build /Applications/MAMP/htdocs/obrella/wp-content/themes/FoundationPress
> grunt build

/Applications/MAMP/htdocs/obrella/wp-content/themes/FoundationPress/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33
    }).flatten().uniq().value();
       ^
TypeError: undefined is not a function
    at Object.module.exports [as findup] (/Applications/MAMP/htdocs/obrella/wp-content/themes/FoundationPress/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33:8)
    at Task.task.init (/Applications/MAMP/htdocs/obrella/wp-content/themes/FoundationPress/node_modules/grunt/lib/grunt/task.js:427:16)
    at Object.grunt.tasks (/Applications/MAMP/htdocs/obrella/wp-content/themes/FoundationPress/node_modules/grunt/lib/grunt.js:120:8)
    at Object.module.exports [as cli] (/Applications/MAMP/htdocs/obrella/wp-content/themes/FoundationPress/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

Here is the npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.13.3
3 info using node@v0.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild foundationpress@1.7.0
6 info build foundationpress@1.7.0
7 verbose unsafe-perm in lifecycle true
8 info foundationpress@1.7.0 Failed to exec build script
9 verbose stack Error: foundationpress@1.7.0 build: `grunt build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid foundationpress@1.7.0
11 verbose cwd /Applications/MAMP/htdocs/obrella/wp-content/themes/FoundationPress
12 error Darwin 15.0.0
13 error argv "node" "/usr/local/bin/npm" "run" "build"
14 error node v0.12.0
15 error npm  v2.13.3
16 error code ELIFECYCLE
17 error foundationpress@1.7.0 build: `grunt build`
17 error Exit status 1
18 error Failed at the foundationpress@1.7.0 build script 'grunt build'.
18 error This is most likely a problem with the foundationpress package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt build
18 error You can get their info via:
18 error     npm owner ls foundationpress
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by BlackSheepWithMe** [comment]
Updated node. Fixed.
