### ISSUE TITLE
path.js throw error, Path must be a string. Received ' + inspect(path);

### ISSUE THREAD

**Issue by shoaibik** [olefredrik/FoundationPress#807]
When I run `npm run production` or `npm run package`, in the process `Starting 'lint'...` it throws the error.

````
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /path-to-fp/www/html/sites/metal/site/wp-content/themes/FoundationPress/node_modules/clean-css/lib/utils/input-source-map-tracker.js:191:56
    at Array.forEach (native)
    at trackContentSources (/path-to-fp/FoundationPress/node_modules/clean-css/lib/utils/input-source-map-tracker.js:188:20)
    at InputSourceMapStore.trackLoaded (/path-to-fp/FoundationPress/node_modules/clean-css/lib/utils/input-source-map-tracker.js:255:3)
    at fromString (/path-to-fp/FoundationPress/node_modules/clean-css/lib/utils/input-source-map-tracker.js:32:8)
    at InputSourceMapStore.track (/path-to-fp/FoundationPress/node_modules/clean-css/lib/utils/input-source-map-tracker.js:236:5)
    at Object.whenDone (/path-to-fp/FoundationPress/node_modules/clean-css/lib/clean.js:145:44)
    at processNext (/path-to-fp/FoundationPress/node_modules/clean-css/lib/imports/inliner.js:105:13)

npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "package"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.6.1 package: `gulp package --production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.6.1 package script 'gulp package --production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp package --production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path-to-fp/FoundationPress/npm-debug.log
```

I am running

- node v 6.0.0
- npm 3.8.6
- ubuntu 14.04 LTS

**Comment by olefredrik** [comment]
This project requires Node.js v4.x.x to be installed on your machine. Please be aware that you may encounter problems with the installation if you are using v5.x.x or v6.x.x

**Comment by shoaibik** [comment]
Thank you, I will try using v4 and will update the issue.

**Comment by olefredrik** [comment]
If you require different versions of Node.js for different project, I would recommend using nvm. https://www.npmjs.com/package/nvm

**Comment by shoaibik** [comment]
Thank you, it worked after using node v4.4.3 and I used nvm.

**Comment by olefredrik** [comment]
Great! Enjoy :)

**Comment by jamivinaysagar** [comment]
node -v
v4.4.7
 npm -v
4.5.0
 I am using as above, still facing the same issue.

**Comment by jamivinaysagar** [comment]
nyc npm run test
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received [ '.nycrc', '.nycrc.json' ]
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at join (/usr/local/lib/node_modules/nyc/node_modules/find-up/index.js:11:14)
    at Function.module.exports.sync (/usr/local/lib/node_modules/nyc/node_modules/find-up/index.js:43:12)
    at Object.Config.loadConfig (/usr/local/lib/node_modules/nyc/lib/config-util.js:17:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/nyc/bin/nyc.js:23:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
