### ISSUE TITLE
npm run watch issue

### ISSUE THREAD

**Issue by kalbers** [olefredrik/FoundationPress#841]
Hi, I'm getting an error when I run npm watch that seems slightly different from a few of the others I've seen here. I have no problem when I run npm build. It does not error out, and it does properly insert changes into foundation.css. Obviously, something of a pain when you're developing, but not the worst thing. Any thoughts would be appreciated.

Here's what I get when I run watch.

> foundationpress@2.6.2 watch /var/www/html/wordpress/wp-content/themes/FoundationPress
> gulp

[12:59:42] Using gulpfile /var/www/html/wordpress/wp-content/themes/FoundationPress/gulpfile.js
[12:59:42] Starting 'clean'...
[12:59:42] Starting 'clean:javascript'...
[12:59:42] Starting 'clean:css'...
[12:59:42] Finished 'clean:css' after 5.63 ms
[12:59:42] Finished 'clean:javascript' after 9.54 ms
[12:59:42] Finished 'clean' after 11 ms
[12:59:42] Starting 'build'...
[12:59:42] Starting 'copy'...
[12:59:43] Finished 'copy' after 76 ms
[12:59:43] Starting 'sass'...
[12:59:43] Starting 'javascript'...
[12:59:43] Starting 'lint'...
[12:59:44] Finished 'lint' after 1.32 s
[12:59:44] Finished 'sass' after 1.95 s
[12:59:47] Finished 'javascript' after 3.96 s
[12:59:47] Finished 'build' after 4.29 s
[12:59:47] Starting 'browser-sync'...
[12:59:47] Finished 'browser-sync' after 11 ms
[12:59:47] Starting 'default'...
[12:59:47] Finished 'default' after 21 ms
[BS] Copy the following snippet into your website, just before the closing </body> tag
<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.2.13.0.js'><\/script>".replace("HOST", location.hostname));
//]]></script>

[BS] Access URLs:
 -------------------------------------
          UI: http://localhost:3001
 -------------------------------------
 UI External: http://192.168.1.83:3001
 -------------------------------------
[BS] Watching files...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/invariant ENOSPC
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/var/www/html/wordpress/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/var/www/html/wordpress/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/var/www/html/wordpress/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/var/www/html/wordpress/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/var/www/html/wordpress/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/var/www/html/wordpress/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 4.3.0-040300-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v5.6.0
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.6.2 watch: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.6.2 watch script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/wordpress/wp-content/themes/FoundationPress/npm-debug.log

**Please List the Following:**
Linux Mint 17.2
node v5.6.0
foundation-sites#6.2.3

**Comment by radel** [comment]
from project requirements:

> This project requires Node.js v4.x.x to be installed on your machine. Please be aware that you may encounter problems with the installation if you are using v5.1.0 with all the latest features.

Could be your node.js version

**Comment by mladenp** [comment]
I have the same issue. Tried different Node versions, not helping. 
Not gulp issue as it runs fine in other projects.

**Comment by radel** [comment]
Did you set the "url" variable in Gulpfile.js? BrowserSync needs a valid url to proxy

**Comment by mladenp** [comment]
Yes. 
But your idea helped. I just removed BrowserSync and its working fine.

**Comment by brianr001** [comment]
Can you specify how exactly you removed BrowserSync? I'm having the same problem and can't seem to figure it out.
