### ISSUE TITLE
npm install and npm run watch errors

### ISSUE THREAD

**Issue by jarrydfillmore** [olefredrik/FoundationPress#843]
I have Node version 4.4.1 installed and npm version 2.14.20 installed.

When starting a new project, I get the following error (excuse the bold / coded styling, I simply pasted from terminal):

Fillmores-MacBook-Pro:FoundationPress Fillmore$ npm install
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
-
> node-sass@3.8.0 install /Applications/MAMP/htdocs/barry/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Applications/MAMP/htdocs/barry/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> fsevents@1.0.12 install /Applications/MAMP/htdocs/barry/wp-content/themes/FoundationPress/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Applications/MAMP/htdocs/barry/wp-content/themes/FoundationPress/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote

> node-sass@3.8.0 postinstall /Applications/MAMP/htdocs/barry/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

"/Applications/MAMP/htdocs/barry/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! path /Users/Fillmore/.npm/duplexify/3.4.3
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/Fillmore/.npm/duplexify/3.4.3'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/Users/Fillmore/.npm/duplexify/3.4.3']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/Fillmore/.npm/duplexify/3.4.3',
npm ERR!   parent: 'ternary-stream' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/barry/wp-content/themes/FoundationPress/npm-debug.log
Fillmores-MacBook-Pro:FoundationPress Fillmore$ npm run watch

> foundationpress@2.6.2 watch /Applications/MAMP/htdocs/barry/wp-content/themes/FoundationPress
> gulp

module.js:327
    throw err;
    ^

Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/barry/wp-content/themes/FoundationPress/gulpfile.js:7:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.6.2 watch: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.6.2 watch script 'gulp'.
npm ERR! This is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/barry/wp-content/themes/FoundationPress/npm-debug.log

Does anyone know the fix?

**Comment by jarrydfillmore** [comment]
Fixed - had to uninstall F5 gem, then use sudo infront of my commands as I'm on a mac.
