### ISSUE TITLE
Error: Cannot find module 'sparkles'

### ISSUE THREAD

**Issue by skoldin** [olefredrik/FoundationPress#867]
cd my-wordpress-folder/wp-content/themes/
git clone https://github.com/olefredrik/FoundationPress.git
cd FoundationPress
npm install

Throws the error: Cannot find module 'sparkles'

foundation-sites#6.2.3

NPM debug log with information about OS, Node version etc attached.

[npm-debug.txt](https://github.com/olefredrik/FoundationPress/files/392996/npm-debug.txt)

**Comment by skoldin** [comment]
Here is what is happening if install sparkles manually:
```
> bower install && gulp build

module.js:328
    throw err;
    ^

Error: Cannot find module 'filename-regex'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\OpenServer\domains\test.dev\wp-content\themes\FoundationPress\node_modules\gulp-load-plugins\node_modules\micromatch\lib\utils.js:5:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.6.2 postinstall: `bower install && gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundationpress@2.6.2 postinstall script 'bower install && gulp build'.
```

**Comment by olefredrik** [comment]
Can I please have your node vesion, npm version and OS?

**Comment by skoldin** [comment]
npm  v2.14.12, node v4.3.0, Windows_NT 10.0.10586

**Comment by olefredrik** [comment]
Just completed two fresh installs; on Mac OSX Sierra and WIndows 10, using the node v.6.9.1 (v4.3.0 should also be fine). Experienced zero errors on `npm install` and zero errors on `npm run build`. Would really like to help you, but I don't see how I can, as I'm unable to recreate the error on my side. Because of that, I will close the issue.
