### ISSUE TITLE
Cannot find open

### ISSUE THREAD

**Issue by MugeshBTech** [olefredrik/FoundationPress#889]
Hi,

 Help on the below error. I have installed open npm globally using the command 'npm instal open -g' but am getting that Cannot find module 'open' 

**ERROR**

C:\Users\is5063\Desktop>npm instal open -g
open@0.0.5 C:\Users\is5063\AppData\Roaming\npm\node_modules\open

C:\Users\is5063\Desktop>node server.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'open'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\is5063\Desktop\server.js:2:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by jklegseth** [comment]
@MugeshBTech you have a typo: `install` not `instal`. I'm surprised npm didn't alert you to that. You can see what packages are installed using `npm ls --depth=0` for local packages and `npm ls -g --depth=0` for global packages.
