### ISSUE TITLE
Sudden error when running "npm run watch"

### ISSUE THREAD

**Issue by pntbutter** [olefredrik/FoundationPress#890]
**How can this bug be reproduced?**
I can't run "npm install" or "npm run watch" without errors even though it worked last week, with no work being done in the time between.

**Please List the Following:**
- OS & version: Windows 10
- Node version (node -v) [Node v4+ is required] : 4.4.7
- Foundation version (bower list) : 2.6.1 (FoundationPress), 6.2.3 (foundationsites)

**Include Test Case** (if applicable):  
npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose readDependencies loading dependencies from C:\Users\user\Desktop\site\wp-content\themes\site\package.json
5 verbose install where, deps [ 'C:\\Users\\user\\Desktop\\site\\wp-content\\themes\\site',
5 verbose install   [] ]
6 verbose install where, peers [ 'C:\\Users\\user\\Desktop\\site\\wp-content\\themes\\site',
6 verbose install   [] ]
7 verbose installManyTop reading for lifecycle C:\Users\user\Desktop\site\wp-content\themes\site\package.json
8 info preinstall foundationpress@2.6.2
9 verbose installManyTop reading scoped package data from C:\Users\user\Desktop\site\wp-content\themes\site\node_modules\gulp\package.json
10 verbose readDependencies loading dependencies from C:\Users\user\Desktop\site\wp-content\themes\site\package.json
11 silly install resolved []
12 info build C:\Users\user\Desktop\site\wp-content\themes\site
13 verbose targetResolver reading package data from C:\Users\user\Desktop\site\wp-content\themes\site\node_modules\gulp\package.json
14 verbose targetResolver reading package data from C:\Users\user\Desktop\site\wp-content\themes\site\node_modules\.bin\gulp\package.json
15 verbose targetResolver reading package data from C:\Users\user\Desktop\site\wp-content\themes\site\node_modules\.bin\gulp.cmd\package.json
16 info linkStuff foundationpress@2.6.2
17 silly linkStuff foundationpress@2.6.2 has C:\Users\user\Desktop\site\wp-content\themes as its parent node_modules
18 verbose linkBins foundationpress@2.6.2
19 verbose linkMans foundationpress@2.6.2
20 verbose rebuildBundles foundationpress@2.6.2
21 verbose rebuildBundles [ '.bin', 'gulp' ]
22 info install foundationpress@2.6.2
23 info postinstall foundationpress@2.6.2
24 verbose unsafe-perm in lifecycle true
25 info foundationpress@2.6.2 Failed to exec postinstall script
26 verbose stack Error: foundationpress@2.6.2 postinstall: `bower install && gulp build`
26 verbose stack Exit status 1
26 verbose stack     at EventEmitter.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v4.4.7\node_modules\npm\lib\utils\lifecycle.js:217:16)
26 verbose stack     at emitTwo (events.js:87:13)
26 verbose stack     at EventEmitter.emit (events.js:172:7)
26 verbose stack     at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v4.4.7\node_modules\npm\lib\utils\spawn.js:24:14)
26 verbose stack     at emitTwo (events.js:87:13)
26 verbose stack     at ChildProcess.emit (events.js:172:7)
26 verbose stack     at maybeClose (internal/child_process.js:827:16)
26 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
27 verbose pkgid foundationpress@2.6.2
28 verbose cwd C:\Users\user\Desktop\site\wp-content\themes\site
29 error Windows_NT 10.0.10586
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
31 error node v4.4.7
32 error npm  v2.15.8
33 error code ELIFECYCLE
34 error foundationpress@2.6.2 postinstall: `bower install && gulp build`
34 error Exit status 1
35 error Failed at the foundationpress@2.6.2 postinstall script 'bower install && gulp build'.
35 error This is most likely a problem with the foundationpress package,
35 error not with npm itself.
35 error Tell the author that this fails on your system:
35 error     bower install && gulp build
35 error You can get information on how to open an issue for this project with:
35 error     npm bugs foundationpress
35 error Or if that isn't available, you can get their info via:
35 error
35 error     npm owner ls foundationpress
35 error There is likely additional logging output above.
36 verbose exit [ 1, true ]
```

Thanks for your time!

**Comment by itsphi1989** [comment]
I had this same issue so I tried "npm cache clean" command and it took a while to complete, then I was able to do "npm install" and "npm run watch".

**Comment by uptownstudios** [comment]
See my answer here: https://github.com/olefredrik/FoundationPress/issues/899#issuecomment-252782775

This fixed this issue for me.

**Comment by olefredrik** [comment]
@pntbutter : Did @itsphi1989 and @uptownstudios suggestions fix the issue for you?

**Comment by olefredrik** [comment]
Because of lack of response, I assume you fixed it. Feel free to reopen if you are still struggling.
