### ISSUE TITLE
Errors while running the production task

### ISSUE THREAD

**Issue by derweili** [olefredrik/FoundationPress#925]
I'm getting an error while running the production task:

```
/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/text/escape-store.js:49
  var index = this.restoreMatcher.exec(placeholder)[1];
                                                   ^

TypeError: Cannot read property '1' of null
    at EscapeStore.restore (/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/text/escape-store.js:49:52)
    at restore (/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/text/comments-processor.js:108:24)
    at CommentsProcessor.restore (/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/text/comments-processor.js:126:10)
    at Object.restoreEscapes [as restore] (/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/clean.js:220:30)
    at store (/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/stringifier/source-maps.js:12:21)
    at selectors (/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/stringifier/helpers.js:55:5)
    at all (/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/stringifier/helpers.js:152:9)
    at stringify (/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/stringifier/source-maps.js:88:3)
    at minify (/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/clean.js:230:10)
    at whenSourceMapReady (/Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/node_modules/clean-css/lib/clean.js:135:7)

npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "production"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.8.0 production: `gulp --production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.8.0 production script 'gulp --production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/arbeitsplatz17/kliniksanktelisabeth/wp-content/themes/kliniksanktelisabeth/npm-debug.log
```

The watch task is running without errors.

I'm no gulp geek but I think that's a problem with the clean-css package. unfortunatly I don't know how to fix this.

I tried the following things but none of them has solved the problem:
I pulled the latest versions of gulpfile and package.json.
I reinstalled node / npm.
I deleted the node_modules folder and run `npm install` again
I updated gulp-clean-css to version 2.2.2

I've following setup:
OSX 10.10
node v6.9.2
npm 3.10.9
foundation-sites 6.2.3

**Comment by parobit** [comment]
Recheck all your sass/scss files and make sure there aren't any syntax errors.

**Comment by derweili** [comment]
Hi,
that's it, thank you for your help. I had a systax error within the foundation.scss.

**Comment by salmuzblues** [comment]
thanks brother, same too me
