### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by jeffdaigle** [olefredrik/FoundationPress#941]
running npm install, FoundationPress 2.9.0.

Running rm -rf node_modules and trying npm install again didn't work.

npm is at 4.1.2 and node.js is at 7.5.0 

Host system is OS X 10.11.6 with the latest distro of Xcode.

All installed npm modules have been updated using the -g flag.

Error output is below:

foundationpress@2.9.0 postinstall /Applications/AMPPS/dbdcdev.com/wp-content/themes/FoundationPress
bower install && gulp build

module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/Applications/AMPPS/dbdcdev.com/wp-content/themes/FoundationPress/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.9.0 postinstall: `bower install && gulp build`
npm ERR! Exit status 1

**Comment by olefredrik** [comment]
Hi @jeffdaigle . Node v7.5.0 is not currently supported. If you install [Node](https://nodejs.org/en/) v6.9.5 (which is recommended for most users) it should work as expected.

**Comment by olefredrik** [comment]
Please let me know how it goes

**Comment by jeffdaigle** [comment]
Now I feel stupid :) It works perfectly now. Thanks!
