### ISSUE TITLE
Installation error: node-sass

### ISSUE THREAD

**Issue by ronanfernandes** [olefredrik/FoundationPress#964]
**How can this bug be reproduced?**

1. Step one -> git clone https://github.com/olefredrik/FoundationPress.git
2. Step two -> Run 'sudo npm install'
3. Step three -> Retried step 2 deleting 'node_modules' before running (no success at all)

**What did you expect to happen?**
Installation complete successfully.

**What happened instead?**
npm WARN prefer global node-gyp@3.6.0 should be installed with -g

> node-sass@3.13.1 install /vagrant/wp/wp-content/themes/FoundationPress/node_modules/node-sass
> node scripts/install.js

/vagrant/wp/wp-content/themes/FoundationPress/node_modules/tough-cookie/lib/pubsuffix.js:96
{"ac":true,"com.ac":true,"edu.ac":true,"gov.ac":true,"net.ac":true,"mil.ac":true,"org.ac":true,"ad":true,"nom.ad":true,"ae":true,"co.ae":true,"net.ae":true,"org.ae":true,"sch.ae":true,"ac.ae":true,"gov.ae":true,"mil.ae":true,"aero":true,"accident-investigation.aero":true,"accident-prevention.aero":true,"aerobatic.aero":true,"aeroclub.aero":true,"aerodrome.aero":true,"agents.aero":true,"aircraft.aero":true,"airline.aero":true,"airport.aero":true,"air-surveillance.aero":true,"airtraffic.aero":true,"air-traffic-control.aero":true,"ambulance.aero":true,"amusement.aero":true,"association.aero":true,"author.aero":true,"ballooning.aero":true,"broker.aero":true,"caa.aero":true,"cargo.aero":true,"catering.aero":true,"certification.aero":true,"championship.aero":true,"charter.aero":true,"civilaviation.aero":true,"club.aero":true,"conference.aero":true,"consultant.aero":true,"consulting.aero":true,"control.aero":true,"council.a
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vagrant/wp/wp-content/themes/FoundationPress/node_modules/tough-cookie/lib/cookie.js:34:17)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/wp/wp-content/themes/FoundationPress/npm-debug.log

**Please List the Following:**
* OS & version: Ubuntu 16.04.2 LTS
* Node version (node -v) [Node v4+ is required] : 6.0
Installed Ruby, gem, Sass, GCC before trying.

**Comment by ronanfernandes** [comment]
Installed another Vagrant Box and the issue is gone.
About Vagrant Boxes: 
VVV and PV: don't even get installed.
Chassis: installs, but get the error above.
Scotch Box: the only one that successfully installs FoundationPress
